name: Build and Release EQUITY Artifacts

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: Grimakis/m100-release-workflow/.github/workflows/release.yml@v1
    with:
      source: src/EQUITY.DO
      ascii-name: EQUITY.DO
      tokenized-name: EQUITY.BA
    secrets: inherit
